### ISSUE TITLE
How to run this project?Thanks!

### ISSUE THREAD

**Issue by Lotus-Blue** [xiaxin1998/EODRec#1]

**Comment by xiaxin1998** [comment]
Thanks for your patience.
To run this project, there are the steps:
1. run main_pretrain.py to get pretrained code matrix and codebooks 
2. run main_student.py to train a student model  and save the well-trained student
3. download the student model into a device and using Pytorch Mobile to encapsulate the student model
4. run the pytorch Mobile model on Android Studio with a selected mobile device virtual system
The required teacher models and Android Studio Project Demo can be accessed in here: https://www.dropbox.com/sh/g4mgdaezr8uqgic/AABpUxvY3_407D-0UNuEzOAMa?dl=0
Note that this paper is an extension of our previous paper (https://github.com/xiaxin1998/OD-Rec) and is undre review.
